/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReferenceRouteRouteImport } from './routes/reference/route'
import { Route as DisplayRouteRouteImport } from './routes/display/route'
import { Route as CampaignIdRouteRouteImport } from './routes/$campaignId/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReferenceIndexRouteImport } from './routes/reference/index'
import { Route as DisplayIndexRouteImport } from './routes/display/index'
import { Route as CampaignIdIndexRouteImport } from './routes/$campaignId/index'
import { Route as ReferenceInjuriesRouteImport } from './routes/reference/injuries'
import { Route as ReferenceCloseCombatWeaponsRouteImport } from './routes/reference/close-combat-weapons'
import { Route as CampaignIdAdminRouteImport } from './routes/$campaignId/admin'
import { Route as DisplayCampaignIdRouteRouteImport } from './routes/display/$campaignId/route'
import { Route as ReferenceScenariosIndexRouteImport } from './routes/reference/scenarios.index'
import { Route as DisplayCampaignIdIndexRouteImport } from './routes/display/$campaignId/index'
import { Route as CampaignIdWarriorsIndexRouteImport } from './routes/$campaignId/warriors/index'
import { Route as CampaignIdWarbandsIndexRouteImport } from './routes/$campaignId/warbands/index'
import { Route as CampaignIdTimelineIndexRouteImport } from './routes/$campaignId/timeline/index'
import { Route as CampaignIdProgressIndexRouteImport } from './routes/$campaignId/progress/index'
import { Route as CampaignIdMatchesIndexRouteImport } from './routes/$campaignId/matches/index'
import { Route as CampaignIdEventsIndexRouteImport } from './routes/$campaignId/events/index'
import { Route as ReferenceScenariosScenarioIdRouteImport } from './routes/reference/scenarios.$scenarioId'
import { Route as DisplayCampaignIdResultsRouteImport } from './routes/display/$campaignId/results'
import { Route as CampaignIdWarriorsWarriorIdRouteImport } from './routes/$campaignId/warriors/$warriorId'
import { Route as CampaignIdMatchesTableRouteImport } from './routes/$campaignId/matches/table'
import { Route as CampaignIdMatchesNewRouteImport } from './routes/$campaignId/matches/new'
import { Route as CampaignIdWarbandsWarbandIdIndexRouteImport } from './routes/$campaignId/warbands/$warbandId/index'
import { Route as CampaignIdMatchesMatchIdIndexRouteImport } from './routes/$campaignId/matches/$matchId/index'
import { Route as CampaignIdMatchesMatchIdPostRouteImport } from './routes/$campaignId/matches/$matchId/post'
import { Route as CampaignIdWarbandsWarbandIdWarriorsWarriorIdRouteImport } from './routes/$campaignId/warbands/$warbandId/warriors/$warriorId'

const ReferenceRouteRoute = ReferenceRouteRouteImport.update({
  id: '/reference',
  path: '/reference',
  getParentRoute: () => rootRouteImport,
} as any)
const DisplayRouteRoute = DisplayRouteRouteImport.update({
  id: '/display',
  path: '/display',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignIdRouteRoute = CampaignIdRouteRouteImport.update({
  id: '/$campaignId',
  path: '/$campaignId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenceIndexRoute = ReferenceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReferenceRouteRoute,
} as any)
const DisplayIndexRoute = DisplayIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DisplayRouteRoute,
} as any)
const CampaignIdIndexRoute = CampaignIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CampaignIdRouteRoute,
} as any)
const ReferenceInjuriesRoute = ReferenceInjuriesRouteImport.update({
  id: '/injuries',
  path: '/injuries',
  getParentRoute: () => ReferenceRouteRoute,
} as any)
const ReferenceCloseCombatWeaponsRoute =
  ReferenceCloseCombatWeaponsRouteImport.update({
    id: '/close-combat-weapons',
    path: '/close-combat-weapons',
    getParentRoute: () => ReferenceRouteRoute,
  } as any)
const CampaignIdAdminRoute = CampaignIdAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => CampaignIdRouteRoute,
} as any)
const DisplayCampaignIdRouteRoute = DisplayCampaignIdRouteRouteImport.update({
  id: '/$campaignId',
  path: '/$campaignId',
  getParentRoute: () => DisplayRouteRoute,
} as any)
const ReferenceScenariosIndexRoute = ReferenceScenariosIndexRouteImport.update({
  id: '/scenarios/',
  path: '/scenarios/',
  getParentRoute: () => ReferenceRouteRoute,
} as any)
const DisplayCampaignIdIndexRoute = DisplayCampaignIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DisplayCampaignIdRouteRoute,
} as any)
const CampaignIdWarriorsIndexRoute = CampaignIdWarriorsIndexRouteImport.update({
  id: '/warriors/',
  path: '/warriors/',
  getParentRoute: () => CampaignIdRouteRoute,
} as any)
const CampaignIdWarbandsIndexRoute = CampaignIdWarbandsIndexRouteImport.update({
  id: '/warbands/',
  path: '/warbands/',
  getParentRoute: () => CampaignIdRouteRoute,
} as any)
const CampaignIdTimelineIndexRoute = CampaignIdTimelineIndexRouteImport.update({
  id: '/timeline/',
  path: '/timeline/',
  getParentRoute: () => CampaignIdRouteRoute,
} as any)
const CampaignIdProgressIndexRoute = CampaignIdProgressIndexRouteImport.update({
  id: '/progress/',
  path: '/progress/',
  getParentRoute: () => CampaignIdRouteRoute,
} as any)
const CampaignIdMatchesIndexRoute = CampaignIdMatchesIndexRouteImport.update({
  id: '/matches/',
  path: '/matches/',
  getParentRoute: () => CampaignIdRouteRoute,
} as any)
const CampaignIdEventsIndexRoute = CampaignIdEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => CampaignIdRouteRoute,
} as any)
const ReferenceScenariosScenarioIdRoute =
  ReferenceScenariosScenarioIdRouteImport.update({
    id: '/scenarios/$scenarioId',
    path: '/scenarios/$scenarioId',
    getParentRoute: () => ReferenceRouteRoute,
  } as any)
const DisplayCampaignIdResultsRoute =
  DisplayCampaignIdResultsRouteImport.update({
    id: '/results',
    path: '/results',
    getParentRoute: () => DisplayCampaignIdRouteRoute,
  } as any)
const CampaignIdWarriorsWarriorIdRoute =
  CampaignIdWarriorsWarriorIdRouteImport.update({
    id: '/warriors/$warriorId',
    path: '/warriors/$warriorId',
    getParentRoute: () => CampaignIdRouteRoute,
  } as any)
const CampaignIdMatchesTableRoute = CampaignIdMatchesTableRouteImport.update({
  id: '/matches/table',
  path: '/matches/table',
  getParentRoute: () => CampaignIdRouteRoute,
} as any)
const CampaignIdMatchesNewRoute = CampaignIdMatchesNewRouteImport.update({
  id: '/matches/new',
  path: '/matches/new',
  getParentRoute: () => CampaignIdRouteRoute,
} as any)
const CampaignIdWarbandsWarbandIdIndexRoute =
  CampaignIdWarbandsWarbandIdIndexRouteImport.update({
    id: '/warbands/$warbandId/',
    path: '/warbands/$warbandId/',
    getParentRoute: () => CampaignIdRouteRoute,
  } as any)
const CampaignIdMatchesMatchIdIndexRoute =
  CampaignIdMatchesMatchIdIndexRouteImport.update({
    id: '/matches/$matchId/',
    path: '/matches/$matchId/',
    getParentRoute: () => CampaignIdRouteRoute,
  } as any)
const CampaignIdMatchesMatchIdPostRoute =
  CampaignIdMatchesMatchIdPostRouteImport.update({
    id: '/matches/$matchId/post',
    path: '/matches/$matchId/post',
    getParentRoute: () => CampaignIdRouteRoute,
  } as any)
const CampaignIdWarbandsWarbandIdWarriorsWarriorIdRoute =
  CampaignIdWarbandsWarbandIdWarriorsWarriorIdRouteImport.update({
    id: '/warbands/$warbandId/warriors/$warriorId',
    path: '/warbands/$warbandId/warriors/$warriorId',
    getParentRoute: () => CampaignIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$campaignId': typeof CampaignIdRouteRouteWithChildren
  '/display': typeof DisplayRouteRouteWithChildren
  '/reference': typeof ReferenceRouteRouteWithChildren
  '/display/$campaignId': typeof DisplayCampaignIdRouteRouteWithChildren
  '/$campaignId/admin': typeof CampaignIdAdminRoute
  '/reference/close-combat-weapons': typeof ReferenceCloseCombatWeaponsRoute
  '/reference/injuries': typeof ReferenceInjuriesRoute
  '/$campaignId/': typeof CampaignIdIndexRoute
  '/display/': typeof DisplayIndexRoute
  '/reference/': typeof ReferenceIndexRoute
  '/$campaignId/matches/new': typeof CampaignIdMatchesNewRoute
  '/$campaignId/matches/table': typeof CampaignIdMatchesTableRoute
  '/$campaignId/warriors/$warriorId': typeof CampaignIdWarriorsWarriorIdRoute
  '/display/$campaignId/results': typeof DisplayCampaignIdResultsRoute
  '/reference/scenarios/$scenarioId': typeof ReferenceScenariosScenarioIdRoute
  '/$campaignId/events': typeof CampaignIdEventsIndexRoute
  '/$campaignId/matches': typeof CampaignIdMatchesIndexRoute
  '/$campaignId/progress': typeof CampaignIdProgressIndexRoute
  '/$campaignId/timeline': typeof CampaignIdTimelineIndexRoute
  '/$campaignId/warbands': typeof CampaignIdWarbandsIndexRoute
  '/$campaignId/warriors': typeof CampaignIdWarriorsIndexRoute
  '/display/$campaignId/': typeof DisplayCampaignIdIndexRoute
  '/reference/scenarios': typeof ReferenceScenariosIndexRoute
  '/$campaignId/matches/$matchId/post': typeof CampaignIdMatchesMatchIdPostRoute
  '/$campaignId/matches/$matchId': typeof CampaignIdMatchesMatchIdIndexRoute
  '/$campaignId/warbands/$warbandId': typeof CampaignIdWarbandsWarbandIdIndexRoute
  '/$campaignId/warbands/$warbandId/warriors/$warriorId': typeof CampaignIdWarbandsWarbandIdWarriorsWarriorIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$campaignId/admin': typeof CampaignIdAdminRoute
  '/reference/close-combat-weapons': typeof ReferenceCloseCombatWeaponsRoute
  '/reference/injuries': typeof ReferenceInjuriesRoute
  '/$campaignId': typeof CampaignIdIndexRoute
  '/display': typeof DisplayIndexRoute
  '/reference': typeof ReferenceIndexRoute
  '/$campaignId/matches/new': typeof CampaignIdMatchesNewRoute
  '/$campaignId/matches/table': typeof CampaignIdMatchesTableRoute
  '/$campaignId/warriors/$warriorId': typeof CampaignIdWarriorsWarriorIdRoute
  '/display/$campaignId/results': typeof DisplayCampaignIdResultsRoute
  '/reference/scenarios/$scenarioId': typeof ReferenceScenariosScenarioIdRoute
  '/$campaignId/events': typeof CampaignIdEventsIndexRoute
  '/$campaignId/matches': typeof CampaignIdMatchesIndexRoute
  '/$campaignId/progress': typeof CampaignIdProgressIndexRoute
  '/$campaignId/timeline': typeof CampaignIdTimelineIndexRoute
  '/$campaignId/warbands': typeof CampaignIdWarbandsIndexRoute
  '/$campaignId/warriors': typeof CampaignIdWarriorsIndexRoute
  '/display/$campaignId': typeof DisplayCampaignIdIndexRoute
  '/reference/scenarios': typeof ReferenceScenariosIndexRoute
  '/$campaignId/matches/$matchId/post': typeof CampaignIdMatchesMatchIdPostRoute
  '/$campaignId/matches/$matchId': typeof CampaignIdMatchesMatchIdIndexRoute
  '/$campaignId/warbands/$warbandId': typeof CampaignIdWarbandsWarbandIdIndexRoute
  '/$campaignId/warbands/$warbandId/warriors/$warriorId': typeof CampaignIdWarbandsWarbandIdWarriorsWarriorIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$campaignId': typeof CampaignIdRouteRouteWithChildren
  '/display': typeof DisplayRouteRouteWithChildren
  '/reference': typeof ReferenceRouteRouteWithChildren
  '/display/$campaignId': typeof DisplayCampaignIdRouteRouteWithChildren
  '/$campaignId/admin': typeof CampaignIdAdminRoute
  '/reference/close-combat-weapons': typeof ReferenceCloseCombatWeaponsRoute
  '/reference/injuries': typeof ReferenceInjuriesRoute
  '/$campaignId/': typeof CampaignIdIndexRoute
  '/display/': typeof DisplayIndexRoute
  '/reference/': typeof ReferenceIndexRoute
  '/$campaignId/matches/new': typeof CampaignIdMatchesNewRoute
  '/$campaignId/matches/table': typeof CampaignIdMatchesTableRoute
  '/$campaignId/warriors/$warriorId': typeof CampaignIdWarriorsWarriorIdRoute
  '/display/$campaignId/results': typeof DisplayCampaignIdResultsRoute
  '/reference/scenarios/$scenarioId': typeof ReferenceScenariosScenarioIdRoute
  '/$campaignId/events/': typeof CampaignIdEventsIndexRoute
  '/$campaignId/matches/': typeof CampaignIdMatchesIndexRoute
  '/$campaignId/progress/': typeof CampaignIdProgressIndexRoute
  '/$campaignId/timeline/': typeof CampaignIdTimelineIndexRoute
  '/$campaignId/warbands/': typeof CampaignIdWarbandsIndexRoute
  '/$campaignId/warriors/': typeof CampaignIdWarriorsIndexRoute
  '/display/$campaignId/': typeof DisplayCampaignIdIndexRoute
  '/reference/scenarios/': typeof ReferenceScenariosIndexRoute
  '/$campaignId/matches/$matchId/post': typeof CampaignIdMatchesMatchIdPostRoute
  '/$campaignId/matches/$matchId/': typeof CampaignIdMatchesMatchIdIndexRoute
  '/$campaignId/warbands/$warbandId/': typeof CampaignIdWarbandsWarbandIdIndexRoute
  '/$campaignId/warbands/$warbandId/warriors/$warriorId': typeof CampaignIdWarbandsWarbandIdWarriorsWarriorIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$campaignId'
    | '/display'
    | '/reference'
    | '/display/$campaignId'
    | '/$campaignId/admin'
    | '/reference/close-combat-weapons'
    | '/reference/injuries'
    | '/$campaignId/'
    | '/display/'
    | '/reference/'
    | '/$campaignId/matches/new'
    | '/$campaignId/matches/table'
    | '/$campaignId/warriors/$warriorId'
    | '/display/$campaignId/results'
    | '/reference/scenarios/$scenarioId'
    | '/$campaignId/events'
    | '/$campaignId/matches'
    | '/$campaignId/progress'
    | '/$campaignId/timeline'
    | '/$campaignId/warbands'
    | '/$campaignId/warriors'
    | '/display/$campaignId/'
    | '/reference/scenarios'
    | '/$campaignId/matches/$matchId/post'
    | '/$campaignId/matches/$matchId'
    | '/$campaignId/warbands/$warbandId'
    | '/$campaignId/warbands/$warbandId/warriors/$warriorId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$campaignId/admin'
    | '/reference/close-combat-weapons'
    | '/reference/injuries'
    | '/$campaignId'
    | '/display'
    | '/reference'
    | '/$campaignId/matches/new'
    | '/$campaignId/matches/table'
    | '/$campaignId/warriors/$warriorId'
    | '/display/$campaignId/results'
    | '/reference/scenarios/$scenarioId'
    | '/$campaignId/events'
    | '/$campaignId/matches'
    | '/$campaignId/progress'
    | '/$campaignId/timeline'
    | '/$campaignId/warbands'
    | '/$campaignId/warriors'
    | '/display/$campaignId'
    | '/reference/scenarios'
    | '/$campaignId/matches/$matchId/post'
    | '/$campaignId/matches/$matchId'
    | '/$campaignId/warbands/$warbandId'
    | '/$campaignId/warbands/$warbandId/warriors/$warriorId'
  id:
    | '__root__'
    | '/'
    | '/$campaignId'
    | '/display'
    | '/reference'
    | '/display/$campaignId'
    | '/$campaignId/admin'
    | '/reference/close-combat-weapons'
    | '/reference/injuries'
    | '/$campaignId/'
    | '/display/'
    | '/reference/'
    | '/$campaignId/matches/new'
    | '/$campaignId/matches/table'
    | '/$campaignId/warriors/$warriorId'
    | '/display/$campaignId/results'
    | '/reference/scenarios/$scenarioId'
    | '/$campaignId/events/'
    | '/$campaignId/matches/'
    | '/$campaignId/progress/'
    | '/$campaignId/timeline/'
    | '/$campaignId/warbands/'
    | '/$campaignId/warriors/'
    | '/display/$campaignId/'
    | '/reference/scenarios/'
    | '/$campaignId/matches/$matchId/post'
    | '/$campaignId/matches/$matchId/'
    | '/$campaignId/warbands/$warbandId/'
    | '/$campaignId/warbands/$warbandId/warriors/$warriorId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CampaignIdRouteRoute: typeof CampaignIdRouteRouteWithChildren
  DisplayRouteRoute: typeof DisplayRouteRouteWithChildren
  ReferenceRouteRoute: typeof ReferenceRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reference': {
      id: '/reference'
      path: '/reference'
      fullPath: '/reference'
      preLoaderRoute: typeof ReferenceRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/display': {
      id: '/display'
      path: '/display'
      fullPath: '/display'
      preLoaderRoute: typeof DisplayRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$campaignId': {
      id: '/$campaignId'
      path: '/$campaignId'
      fullPath: '/$campaignId'
      preLoaderRoute: typeof CampaignIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference/': {
      id: '/reference/'
      path: '/'
      fullPath: '/reference/'
      preLoaderRoute: typeof ReferenceIndexRouteImport
      parentRoute: typeof ReferenceRouteRoute
    }
    '/display/': {
      id: '/display/'
      path: '/'
      fullPath: '/display/'
      preLoaderRoute: typeof DisplayIndexRouteImport
      parentRoute: typeof DisplayRouteRoute
    }
    '/$campaignId/': {
      id: '/$campaignId/'
      path: '/'
      fullPath: '/$campaignId/'
      preLoaderRoute: typeof CampaignIdIndexRouteImport
      parentRoute: typeof CampaignIdRouteRoute
    }
    '/reference/injuries': {
      id: '/reference/injuries'
      path: '/injuries'
      fullPath: '/reference/injuries'
      preLoaderRoute: typeof ReferenceInjuriesRouteImport
      parentRoute: typeof ReferenceRouteRoute
    }
    '/reference/close-combat-weapons': {
      id: '/reference/close-combat-weapons'
      path: '/close-combat-weapons'
      fullPath: '/reference/close-combat-weapons'
      preLoaderRoute: typeof ReferenceCloseCombatWeaponsRouteImport
      parentRoute: typeof ReferenceRouteRoute
    }
    '/$campaignId/admin': {
      id: '/$campaignId/admin'
      path: '/admin'
      fullPath: '/$campaignId/admin'
      preLoaderRoute: typeof CampaignIdAdminRouteImport
      parentRoute: typeof CampaignIdRouteRoute
    }
    '/display/$campaignId': {
      id: '/display/$campaignId'
      path: '/$campaignId'
      fullPath: '/display/$campaignId'
      preLoaderRoute: typeof DisplayCampaignIdRouteRouteImport
      parentRoute: typeof DisplayRouteRoute
    }
    '/reference/scenarios/': {
      id: '/reference/scenarios/'
      path: '/scenarios'
      fullPath: '/reference/scenarios'
      preLoaderRoute: typeof ReferenceScenariosIndexRouteImport
      parentRoute: typeof ReferenceRouteRoute
    }
    '/display/$campaignId/': {
      id: '/display/$campaignId/'
      path: '/'
      fullPath: '/display/$campaignId/'
      preLoaderRoute: typeof DisplayCampaignIdIndexRouteImport
      parentRoute: typeof DisplayCampaignIdRouteRoute
    }
    '/$campaignId/warriors/': {
      id: '/$campaignId/warriors/'
      path: '/warriors'
      fullPath: '/$campaignId/warriors'
      preLoaderRoute: typeof CampaignIdWarriorsIndexRouteImport
      parentRoute: typeof CampaignIdRouteRoute
    }
    '/$campaignId/warbands/': {
      id: '/$campaignId/warbands/'
      path: '/warbands'
      fullPath: '/$campaignId/warbands'
      preLoaderRoute: typeof CampaignIdWarbandsIndexRouteImport
      parentRoute: typeof CampaignIdRouteRoute
    }
    '/$campaignId/timeline/': {
      id: '/$campaignId/timeline/'
      path: '/timeline'
      fullPath: '/$campaignId/timeline'
      preLoaderRoute: typeof CampaignIdTimelineIndexRouteImport
      parentRoute: typeof CampaignIdRouteRoute
    }
    '/$campaignId/progress/': {
      id: '/$campaignId/progress/'
      path: '/progress'
      fullPath: '/$campaignId/progress'
      preLoaderRoute: typeof CampaignIdProgressIndexRouteImport
      parentRoute: typeof CampaignIdRouteRoute
    }
    '/$campaignId/matches/': {
      id: '/$campaignId/matches/'
      path: '/matches'
      fullPath: '/$campaignId/matches'
      preLoaderRoute: typeof CampaignIdMatchesIndexRouteImport
      parentRoute: typeof CampaignIdRouteRoute
    }
    '/$campaignId/events/': {
      id: '/$campaignId/events/'
      path: '/events'
      fullPath: '/$campaignId/events'
      preLoaderRoute: typeof CampaignIdEventsIndexRouteImport
      parentRoute: typeof CampaignIdRouteRoute
    }
    '/reference/scenarios/$scenarioId': {
      id: '/reference/scenarios/$scenarioId'
      path: '/scenarios/$scenarioId'
      fullPath: '/reference/scenarios/$scenarioId'
      preLoaderRoute: typeof ReferenceScenariosScenarioIdRouteImport
      parentRoute: typeof ReferenceRouteRoute
    }
    '/display/$campaignId/results': {
      id: '/display/$campaignId/results'
      path: '/results'
      fullPath: '/display/$campaignId/results'
      preLoaderRoute: typeof DisplayCampaignIdResultsRouteImport
      parentRoute: typeof DisplayCampaignIdRouteRoute
    }
    '/$campaignId/warriors/$warriorId': {
      id: '/$campaignId/warriors/$warriorId'
      path: '/warriors/$warriorId'
      fullPath: '/$campaignId/warriors/$warriorId'
      preLoaderRoute: typeof CampaignIdWarriorsWarriorIdRouteImport
      parentRoute: typeof CampaignIdRouteRoute
    }
    '/$campaignId/matches/table': {
      id: '/$campaignId/matches/table'
      path: '/matches/table'
      fullPath: '/$campaignId/matches/table'
      preLoaderRoute: typeof CampaignIdMatchesTableRouteImport
      parentRoute: typeof CampaignIdRouteRoute
    }
    '/$campaignId/matches/new': {
      id: '/$campaignId/matches/new'
      path: '/matches/new'
      fullPath: '/$campaignId/matches/new'
      preLoaderRoute: typeof CampaignIdMatchesNewRouteImport
      parentRoute: typeof CampaignIdRouteRoute
    }
    '/$campaignId/warbands/$warbandId/': {
      id: '/$campaignId/warbands/$warbandId/'
      path: '/warbands/$warbandId'
      fullPath: '/$campaignId/warbands/$warbandId'
      preLoaderRoute: typeof CampaignIdWarbandsWarbandIdIndexRouteImport
      parentRoute: typeof CampaignIdRouteRoute
    }
    '/$campaignId/matches/$matchId/': {
      id: '/$campaignId/matches/$matchId/'
      path: '/matches/$matchId'
      fullPath: '/$campaignId/matches/$matchId'
      preLoaderRoute: typeof CampaignIdMatchesMatchIdIndexRouteImport
      parentRoute: typeof CampaignIdRouteRoute
    }
    '/$campaignId/matches/$matchId/post': {
      id: '/$campaignId/matches/$matchId/post'
      path: '/matches/$matchId/post'
      fullPath: '/$campaignId/matches/$matchId/post'
      preLoaderRoute: typeof CampaignIdMatchesMatchIdPostRouteImport
      parentRoute: typeof CampaignIdRouteRoute
    }
    '/$campaignId/warbands/$warbandId/warriors/$warriorId': {
      id: '/$campaignId/warbands/$warbandId/warriors/$warriorId'
      path: '/warbands/$warbandId/warriors/$warriorId'
      fullPath: '/$campaignId/warbands/$warbandId/warriors/$warriorId'
      preLoaderRoute: typeof CampaignIdWarbandsWarbandIdWarriorsWarriorIdRouteImport
      parentRoute: typeof CampaignIdRouteRoute
    }
  }
}

interface CampaignIdRouteRouteChildren {
  CampaignIdAdminRoute: typeof CampaignIdAdminRoute
  CampaignIdIndexRoute: typeof CampaignIdIndexRoute
  CampaignIdMatchesNewRoute: typeof CampaignIdMatchesNewRoute
  CampaignIdMatchesTableRoute: typeof CampaignIdMatchesTableRoute
  CampaignIdWarriorsWarriorIdRoute: typeof CampaignIdWarriorsWarriorIdRoute
  CampaignIdEventsIndexRoute: typeof CampaignIdEventsIndexRoute
  CampaignIdMatchesIndexRoute: typeof CampaignIdMatchesIndexRoute
  CampaignIdProgressIndexRoute: typeof CampaignIdProgressIndexRoute
  CampaignIdTimelineIndexRoute: typeof CampaignIdTimelineIndexRoute
  CampaignIdWarbandsIndexRoute: typeof CampaignIdWarbandsIndexRoute
  CampaignIdWarriorsIndexRoute: typeof CampaignIdWarriorsIndexRoute
  CampaignIdMatchesMatchIdPostRoute: typeof CampaignIdMatchesMatchIdPostRoute
  CampaignIdMatchesMatchIdIndexRoute: typeof CampaignIdMatchesMatchIdIndexRoute
  CampaignIdWarbandsWarbandIdIndexRoute: typeof CampaignIdWarbandsWarbandIdIndexRoute
  CampaignIdWarbandsWarbandIdWarriorsWarriorIdRoute: typeof CampaignIdWarbandsWarbandIdWarriorsWarriorIdRoute
}

const CampaignIdRouteRouteChildren: CampaignIdRouteRouteChildren = {
  CampaignIdAdminRoute: CampaignIdAdminRoute,
  CampaignIdIndexRoute: CampaignIdIndexRoute,
  CampaignIdMatchesNewRoute: CampaignIdMatchesNewRoute,
  CampaignIdMatchesTableRoute: CampaignIdMatchesTableRoute,
  CampaignIdWarriorsWarriorIdRoute: CampaignIdWarriorsWarriorIdRoute,
  CampaignIdEventsIndexRoute: CampaignIdEventsIndexRoute,
  CampaignIdMatchesIndexRoute: CampaignIdMatchesIndexRoute,
  CampaignIdProgressIndexRoute: CampaignIdProgressIndexRoute,
  CampaignIdTimelineIndexRoute: CampaignIdTimelineIndexRoute,
  CampaignIdWarbandsIndexRoute: CampaignIdWarbandsIndexRoute,
  CampaignIdWarriorsIndexRoute: CampaignIdWarriorsIndexRoute,
  CampaignIdMatchesMatchIdPostRoute: CampaignIdMatchesMatchIdPostRoute,
  CampaignIdMatchesMatchIdIndexRoute: CampaignIdMatchesMatchIdIndexRoute,
  CampaignIdWarbandsWarbandIdIndexRoute: CampaignIdWarbandsWarbandIdIndexRoute,
  CampaignIdWarbandsWarbandIdWarriorsWarriorIdRoute:
    CampaignIdWarbandsWarbandIdWarriorsWarriorIdRoute,
}

const CampaignIdRouteRouteWithChildren = CampaignIdRouteRoute._addFileChildren(
  CampaignIdRouteRouteChildren,
)

interface DisplayCampaignIdRouteRouteChildren {
  DisplayCampaignIdResultsRoute: typeof DisplayCampaignIdResultsRoute
  DisplayCampaignIdIndexRoute: typeof DisplayCampaignIdIndexRoute
}

const DisplayCampaignIdRouteRouteChildren: DisplayCampaignIdRouteRouteChildren =
  {
    DisplayCampaignIdResultsRoute: DisplayCampaignIdResultsRoute,
    DisplayCampaignIdIndexRoute: DisplayCampaignIdIndexRoute,
  }

const DisplayCampaignIdRouteRouteWithChildren =
  DisplayCampaignIdRouteRoute._addFileChildren(
    DisplayCampaignIdRouteRouteChildren,
  )

interface DisplayRouteRouteChildren {
  DisplayCampaignIdRouteRoute: typeof DisplayCampaignIdRouteRouteWithChildren
  DisplayIndexRoute: typeof DisplayIndexRoute
}

const DisplayRouteRouteChildren: DisplayRouteRouteChildren = {
  DisplayCampaignIdRouteRoute: DisplayCampaignIdRouteRouteWithChildren,
  DisplayIndexRoute: DisplayIndexRoute,
}

const DisplayRouteRouteWithChildren = DisplayRouteRoute._addFileChildren(
  DisplayRouteRouteChildren,
)

interface ReferenceRouteRouteChildren {
  ReferenceCloseCombatWeaponsRoute: typeof ReferenceCloseCombatWeaponsRoute
  ReferenceInjuriesRoute: typeof ReferenceInjuriesRoute
  ReferenceIndexRoute: typeof ReferenceIndexRoute
  ReferenceScenariosScenarioIdRoute: typeof ReferenceScenariosScenarioIdRoute
  ReferenceScenariosIndexRoute: typeof ReferenceScenariosIndexRoute
}

const ReferenceRouteRouteChildren: ReferenceRouteRouteChildren = {
  ReferenceCloseCombatWeaponsRoute: ReferenceCloseCombatWeaponsRoute,
  ReferenceInjuriesRoute: ReferenceInjuriesRoute,
  ReferenceIndexRoute: ReferenceIndexRoute,
  ReferenceScenariosScenarioIdRoute: ReferenceScenariosScenarioIdRoute,
  ReferenceScenariosIndexRoute: ReferenceScenariosIndexRoute,
}

const ReferenceRouteRouteWithChildren = ReferenceRouteRoute._addFileChildren(
  ReferenceRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CampaignIdRouteRoute: CampaignIdRouteRouteWithChildren,
  DisplayRouteRoute: DisplayRouteRouteWithChildren,
  ReferenceRouteRoute: ReferenceRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
