/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CampaignRouteRouteImport } from './routes/$campaign/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReferenceIndexRouteImport } from './routes/reference/index'
import { Route as CampaignIndexRouteImport } from './routes/$campaign/index'
import { Route as ReferenceInjuriesRouteImport } from './routes/reference/injuries'
import { Route as CampaignWarbandsIndexRouteImport } from './routes/$campaign/warbands/index'
import { Route as CampaignMatchesIndexRouteImport } from './routes/$campaign/matches/index'
import { Route as CampaignWarbandsWarbandIndexRouteImport } from './routes/$campaign/warbands/$warband/index'
import { Route as CampaignWarbandsWarbandWarriorsWarriorRouteImport } from './routes/$campaign/warbands/$warband/warriors/$warrior'

const CampaignRouteRoute = CampaignRouteRouteImport.update({
  id: '/$campaign',
  path: '/$campaign',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenceIndexRoute = ReferenceIndexRouteImport.update({
  id: '/reference/',
  path: '/reference/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignIndexRoute = CampaignIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CampaignRouteRoute,
} as any)
const ReferenceInjuriesRoute = ReferenceInjuriesRouteImport.update({
  id: '/reference/injuries',
  path: '/reference/injuries',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignWarbandsIndexRoute = CampaignWarbandsIndexRouteImport.update({
  id: '/warbands/',
  path: '/warbands/',
  getParentRoute: () => CampaignRouteRoute,
} as any)
const CampaignMatchesIndexRoute = CampaignMatchesIndexRouteImport.update({
  id: '/matches/',
  path: '/matches/',
  getParentRoute: () => CampaignRouteRoute,
} as any)
const CampaignWarbandsWarbandIndexRoute =
  CampaignWarbandsWarbandIndexRouteImport.update({
    id: '/warbands/$warband/',
    path: '/warbands/$warband/',
    getParentRoute: () => CampaignRouteRoute,
  } as any)
const CampaignWarbandsWarbandWarriorsWarriorRoute =
  CampaignWarbandsWarbandWarriorsWarriorRouteImport.update({
    id: '/warbands/$warband/warriors/$warrior',
    path: '/warbands/$warband/warriors/$warrior',
    getParentRoute: () => CampaignRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$campaign': typeof CampaignRouteRouteWithChildren
  '/reference/injuries': typeof ReferenceInjuriesRoute
  '/$campaign/': typeof CampaignIndexRoute
  '/reference': typeof ReferenceIndexRoute
  '/$campaign/matches': typeof CampaignMatchesIndexRoute
  '/$campaign/warbands': typeof CampaignWarbandsIndexRoute
  '/$campaign/warbands/$warband': typeof CampaignWarbandsWarbandIndexRoute
  '/$campaign/warbands/$warband/warriors/$warrior': typeof CampaignWarbandsWarbandWarriorsWarriorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reference/injuries': typeof ReferenceInjuriesRoute
  '/$campaign': typeof CampaignIndexRoute
  '/reference': typeof ReferenceIndexRoute
  '/$campaign/matches': typeof CampaignMatchesIndexRoute
  '/$campaign/warbands': typeof CampaignWarbandsIndexRoute
  '/$campaign/warbands/$warband': typeof CampaignWarbandsWarbandIndexRoute
  '/$campaign/warbands/$warband/warriors/$warrior': typeof CampaignWarbandsWarbandWarriorsWarriorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$campaign': typeof CampaignRouteRouteWithChildren
  '/reference/injuries': typeof ReferenceInjuriesRoute
  '/$campaign/': typeof CampaignIndexRoute
  '/reference/': typeof ReferenceIndexRoute
  '/$campaign/matches/': typeof CampaignMatchesIndexRoute
  '/$campaign/warbands/': typeof CampaignWarbandsIndexRoute
  '/$campaign/warbands/$warband/': typeof CampaignWarbandsWarbandIndexRoute
  '/$campaign/warbands/$warband/warriors/$warrior': typeof CampaignWarbandsWarbandWarriorsWarriorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$campaign'
    | '/reference/injuries'
    | '/$campaign/'
    | '/reference'
    | '/$campaign/matches'
    | '/$campaign/warbands'
    | '/$campaign/warbands/$warband'
    | '/$campaign/warbands/$warband/warriors/$warrior'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/reference/injuries'
    | '/$campaign'
    | '/reference'
    | '/$campaign/matches'
    | '/$campaign/warbands'
    | '/$campaign/warbands/$warband'
    | '/$campaign/warbands/$warband/warriors/$warrior'
  id:
    | '__root__'
    | '/'
    | '/$campaign'
    | '/reference/injuries'
    | '/$campaign/'
    | '/reference/'
    | '/$campaign/matches/'
    | '/$campaign/warbands/'
    | '/$campaign/warbands/$warband/'
    | '/$campaign/warbands/$warband/warriors/$warrior'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CampaignRouteRoute: typeof CampaignRouteRouteWithChildren
  ReferenceInjuriesRoute: typeof ReferenceInjuriesRoute
  ReferenceIndexRoute: typeof ReferenceIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$campaign': {
      id: '/$campaign'
      path: '/$campaign'
      fullPath: '/$campaign'
      preLoaderRoute: typeof CampaignRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference/': {
      id: '/reference/'
      path: '/reference'
      fullPath: '/reference'
      preLoaderRoute: typeof ReferenceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$campaign/': {
      id: '/$campaign/'
      path: '/'
      fullPath: '/$campaign/'
      preLoaderRoute: typeof CampaignIndexRouteImport
      parentRoute: typeof CampaignRouteRoute
    }
    '/reference/injuries': {
      id: '/reference/injuries'
      path: '/reference/injuries'
      fullPath: '/reference/injuries'
      preLoaderRoute: typeof ReferenceInjuriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$campaign/warbands/': {
      id: '/$campaign/warbands/'
      path: '/warbands'
      fullPath: '/$campaign/warbands'
      preLoaderRoute: typeof CampaignWarbandsIndexRouteImport
      parentRoute: typeof CampaignRouteRoute
    }
    '/$campaign/matches/': {
      id: '/$campaign/matches/'
      path: '/matches'
      fullPath: '/$campaign/matches'
      preLoaderRoute: typeof CampaignMatchesIndexRouteImport
      parentRoute: typeof CampaignRouteRoute
    }
    '/$campaign/warbands/$warband/': {
      id: '/$campaign/warbands/$warband/'
      path: '/warbands/$warband'
      fullPath: '/$campaign/warbands/$warband'
      preLoaderRoute: typeof CampaignWarbandsWarbandIndexRouteImport
      parentRoute: typeof CampaignRouteRoute
    }
    '/$campaign/warbands/$warband/warriors/$warrior': {
      id: '/$campaign/warbands/$warband/warriors/$warrior'
      path: '/warbands/$warband/warriors/$warrior'
      fullPath: '/$campaign/warbands/$warband/warriors/$warrior'
      preLoaderRoute: typeof CampaignWarbandsWarbandWarriorsWarriorRouteImport
      parentRoute: typeof CampaignRouteRoute
    }
  }
}

interface CampaignRouteRouteChildren {
  CampaignIndexRoute: typeof CampaignIndexRoute
  CampaignMatchesIndexRoute: typeof CampaignMatchesIndexRoute
  CampaignWarbandsIndexRoute: typeof CampaignWarbandsIndexRoute
  CampaignWarbandsWarbandIndexRoute: typeof CampaignWarbandsWarbandIndexRoute
  CampaignWarbandsWarbandWarriorsWarriorRoute: typeof CampaignWarbandsWarbandWarriorsWarriorRoute
}

const CampaignRouteRouteChildren: CampaignRouteRouteChildren = {
  CampaignIndexRoute: CampaignIndexRoute,
  CampaignMatchesIndexRoute: CampaignMatchesIndexRoute,
  CampaignWarbandsIndexRoute: CampaignWarbandsIndexRoute,
  CampaignWarbandsWarbandIndexRoute: CampaignWarbandsWarbandIndexRoute,
  CampaignWarbandsWarbandWarriorsWarriorRoute:
    CampaignWarbandsWarbandWarriorsWarriorRoute,
}

const CampaignRouteRouteWithChildren = CampaignRouteRoute._addFileChildren(
  CampaignRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CampaignRouteRoute: CampaignRouteRouteWithChildren,
  ReferenceInjuriesRoute: ReferenceInjuriesRoute,
  ReferenceIndexRoute: ReferenceIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
